### ISSUE TITLE
Add mastodon handler to the frontpage/footer.

### ISSUE THREAD

**Issue by mariha** [OpenHospitalityNetwork/sleepy-bike-solid#56]
Add a link to mastodon profile to the frontpage. It should have `rel="me"` attribute so that our account can be trusted as being owned by `sleepy.bike` in our mastodon profile metadata (it will show as verified).

```
<a rel="me" href="https://floss.social/@sleepybike">mastodon</a>
```

The link can be a text or maybe mastodon logo (next to GH and OC logos?).

**Comment by mariha** [comment]
The same can be applied to FB profile `https://www.facebook.com/SleepyBikePage/`

**Comment by mariha** [comment]
Upps, our profile is still not verified as being owned by sleepy.bike website.

https://floss.social/settings/verification

> Tip: The link on your website can be invisible. The important part is rel="me" which prevents impersonation on websites with user-generated content. You can even use a link tag in the header of the page instead of a, but **the HTML must be accessible without executing JavaScript.**

**Comment by mrkvon** [comment]
@mariha It still doesn't seem to be verified. Is there some action on the side of Mastodon that needs to be performed in order for the verification to be finished?

**Comment by mariha** [comment]
There was - I had to re-enter the property. After that it works as expected.
