### ISSUE TITLE
Solid server at solidweb.me may need support to keep operating

### ISSUE THREAD

**Issue by mrkvon** [OpenHospitalityNetwork/sleepy-bike-solid#91]
The server solidweb.me is [deprecated](https://solidweb.me/somewhereelse/index.html). It's an issue for sleepy.bike, because we have around 50 of the first ~100 members registered there.

This situation also clearly highlights weak spot of Solid, which is dependency of identities and relationships on domain names.

Possible next steps:

- [x] remove solidweb.me from recommended options for sign-up #93 
- [x] offer @ewingson help with maintenance of solidweb.me or other form of support, or offer taking ownership of solidweb.me (as some dedicated team) with goal of keeping solidweb.me up in the longer-term future. (preferred)
- [ ] warn members who registered with solidweb.me that their account will disappear, and help them migrate somewhere else (fallback)
- ...

---

Currently, [the site says](https://web.archive.org/web/20240317165859/https://solidweb.me/somewhereelse/index.html):

> Welcome to the (deprecated) 6.1.0 version of the Community Solid Server.
> This server is located in Strasbourg, France and is around since estimated September 2021.
> Development has happened.
> Because this site is implemented and maintained in a hobbyist and autodidactic manner it does not match up-to-date security standards.
> It has become increasingly difficult to keep the production Debian 10 machine running Solid with an underlying Nginx in a way that is maintainable and manageable to be sufficient useful for the community.
> 
> But it is understandable for the author that we can't simply take the site offline.
> Momentary daily 502 outages take place. We restart the machine manually whenever we get aware and consider using pm2 monitoring software.
> 
> The learning curve while deploying and running this system was and is invaluable.
> The time for this machine is running down.
> We encourage everyone to migrate sensible user data to a more secure provider. You might want to use tools of Jeff Zucker, Otto-AA or www.muze.nl for these processes.
> 
> If I may add a personal experience, since I was onboarded in 2018 by Mitzi, uncountable learning lessons were made.
> The account data is triple backup'ed and weekly backups are still done.
> Estimated year turn 2024/2025 we will take the site offline.
> 
> As of Sun 2024-03-17 we have 543 accounts. Thank you.

**Comment by ewingson** [comment]
@mrkvon @mariha 

a) the site and IDP will stay online for as long as necessary.
b) if I get aware of 502 errors (Bad Gateway) I will immediately do a `systemctl restart communityss.service`.
c) with [deprecated] I meant that 6.1.0 is not the actual version, which is a 7.0.4 (https://www.npmjs.com/package/@solid/community-server).

I just *had* to take some action, the safety/security of the system definitely needs some TLC.
one possible solution might be pm2 or some team effort.

as mentioned in the chat I am just one person juggling with an Debian 10 and an Debian 11 system trying to serve the community with helpful services.
I am open for collaboration and would be thankful for any kind of help.
let's do some sync/async work towards a secure server.

for sure I will try not do a one-man-show decision and rest open for communication, education and guidance.
maybe an examination of the system logs can show the reasons for the 502s.

any more ideas anyone ?
tag anyone ?

the server and domain is signed at www.hosteurope.de.
understand me. talk to me.

**Comment by mrkvon** [comment]
@ewingson I'm very grateful for the effort and resources you have been giving into running solidweb.me. I also understand that it is challenging and time-consuming to single-handedly care about it. I opened this issue to inform our project about the challenges that may arise if it goes offline, and to try to find solutions. I definitely didn't mean to criticize or complain. I think the server has been very special because it offered the first option online to try out CSS (afaik), and has kept running consistently for several years already.

I think i mixed the terms. I used the term _deprecated_ because i read

> Estimated year turn 2024/2025 we will take the site offline.

It actually sounds to me like this is a worst-case scenario, and you would potentially be happy to keep the server up beyond this date if there's sufficient support in maintaining it. Is that correct? Let's explore that possibility!

I know at least one reliable way to put CSS server down. So the 502 outages are bound to happen. If we manage to automate its restart, that should already make a difference, right?  Can't promise, but i think the automation with pm2 may be relatively low-hanging fruit.

Let's keep in contact about this! 🙂

**Comment by ewingson** [comment]
@mrkvon

I am happy to keep the conversation going forward, constructively, and in this thread opposed to the chat, cause it is more persistent and documented.
tonight I see (not sure if momentary or long-term-anticipating) a possible path.

- [x] doing an evaluation of the situation (sync)
- [x] make `pm2` work (I have an account on https://pm2.io/ and I have an archived command which I am not sure if it's correct) (async?)
- [ ] maybe with these steps the existence of the insecure System Unit user already loses its importance
- [ ] if we're really good, maybe updating solidweb.me to 7.0.4 (bonus)
- [ ] designing a usable `index.html` with all necessary information for existing users as well as info to sign-up (cherry-on-top, feel educated enough to do this alone)

> It actually sounds to me like this is a worst-case scenario, and you would potentially be happy to keep the server up beyond this date if there's sufficient support in maintaining it.

yes, this analysis is correct.
nevertheless I will leave the current homepage online (kindof an 'open letter').

what do you think of a time window for a video chat between saturday, March 23rd, 9:00 UTC and sunday, March 24th, 23:00 UTC (I'm in GMT+01 timezone) ?

I am reading the matrix regularly and am on github daily, and on info@meisdata.io

what do you think ?
in principle, I trust you sufficiently to give you temporary `ssh`-access if you send me a ssh-keyfile, but maybe that's not necessary, and ***please*** be careful cause it's a production system and a single mistake can fuck up the whole system.

sounds like a way forward ?

**Comment by ewingson** [comment]
serve the homepage is okay with pm2.
the bad news: no functional login.

solidweb.me (6.1.0) says 502
teamid.live (7.0.4) says `InternalServerError: Unable to access file used for constant conversion.`

I use `pm2 start script.sh` with

```
/root/.nvm/versions/node/v16.17.0/bin/node /data/css/Recipes/mashlib/node_modules/@solid/community-server/bin/server.js -c @css:config/config-mashlib.json -f /var/www/solidweb.me -b https://solidweb.me/
```

partly success but not usable.
I am lost without help.

the syntax I use is \<command> \<server> \<parameters>

possible to use npm or npx ?

[edit] I did find https://github.com/solid/solidcommunity.net/wiki/solidcommunity.net-servers#2-css-suffix-test-server-httpssolidcommunitynet3001 but it did not work

[edit2] can you test if the server is usable in the current state for your sleepy.bike users ? got hope...

**Comment by mrkvon** [comment]
> I am happy to keep the conversation going forward, constructively, and in this thread opposed to the chat, cause it is more persistent and documented.

I feel slightly overwhelmed from the idea of chatting on GitHub. I'd personally prefer to separate concerns a bit. Would it work for you e.g. to use GitHub to document the progress, but keep the chat and general back-and-forth on Matrix? I think it may also be beneficial to document the progress regarding solidweb.me e.g. on https://github.com/ewingson/solidweb.me, and use this thread to keep track of solidweb.me in relation to sleepy.bike.

I like the points you proposed, let's start tackling them.

> what do you think of a time window for a video chat between saturday, March 23rd, 9:00 UTC and sunday, March 24th, 23:00 UTC (I'm in GMT+01 timezone) ?

That works for me.

> in principle, I trust you sufficiently to give you temporary ssh-access if you send me a ssh-keyfile, but maybe that's not necessary, and please be careful cause it's a production system and a single mistake can fuck up the whole system.

Let's start without that access. I think videocall with screensharing can already be a viable format.

> can you test if the server is usable in the current state for your sleepy.bike users ? got hope...

I can see solidweb.me users on the map, which is a good indication.

**Comment by mrkvon** [comment]
> I use `pm2 start script.sh` with
> 
> ```
> /root/.nvm/versions/node/v16.17.0/bin/node /data/css/Recipes/mashlib/node_modules/@solid/community-server/bin/server.js -c @css:config/config-mashlib.json -f /var/www/solidweb.me -b https://solidweb.me/
> ```
> 
> partly success but not usable.

I find it peculiar that you run CSS from node_modules of other project, and not directly. Is that on purpose?

**Comment by mrkvon** [comment]
I'll write more informally on Matrix chat... 🙂

**Comment by ewingson** [comment]
- the directory `node_modules` is the one I am running https://github.com/CommunitySolidServer/Recipes/tree/main/mashlib in
- I have documented in https://github.com/serverproject-dev/solidweb.me/issues/3

**Comment by ewingson** [comment]
solved as per https://github.com/serverproject-dev/solidweb.me/issues/3#issuecomment-2016481417

@ Michal and Mariha

we will for sure not take solidweb.me offline from one day to another.
the good thing is, the whole system seems flexible enough to switch providers and let apps this way operate non-regarding the location of the backend.

**Comment by mrkvon** [comment]
I wrote detailed instructions how to set up CSS in production: https://github.com/mrkvon/css-setup

I also tested it, and it works.

Feedback much appreciated!

**Comment by mrkvon** [comment]
I've added solidweb.me back to recommended providers per #113.

@ewingson Thank you, and please feel free to reopen if relevant or reach out if help is needed! ❤️

**Comment by ewingson** [comment]
@mrkvon 

thanx.
the thing is alive.
the ip is 46.163.118.221
the source is on https://github.com/serverproject-dev/solidweb.me/blob/main/src/index.html
I don't do a lot of maintaining, just certs and version updates,
but from my side it can run from now on into eternity....

;-)
